### ISSUE TITLE
[Bug] No exported member named 'TransactionService'. 

### ISSUE THREAD

**Issue by premiermatt** [jamesmcroft/opayo-form-integration-for-js#26]
### Describe the bug

First off, thanks for putting this out there. The SagePay/Opayo encryption spec do not seem to be working for me with crypto-js.  This is just what I'm looking for.

I've installed this package within my Nuxt3 project, imported the example code and I receive the error.  

`'"opayo-form-integration-js"' has no exported member named 'TransactionService'. Did you mean 'ITransactionService'?
`

### Other information

EDIT - Closing this as the source files in this package helped me successfully use crypto-js. Very helpful, thanks.

**Comment by jamesmcroft** [comment]
I will still have a look into this for you and make sure that this works as expect with Nuxt

**Comment by jamesmcroft** [comment]
@premiermatt this should be fixed in latest release now. Thanks for raising the issue.
